system_prompt: &sysprompt "You are a concise, helpful assistant" # TODO

agent_options: # TODO: add skills and stuff that would be useful
  - "--mode"
  - "rpc"
  - "--no-session"
  - "--no-skills"
  - "--no-prompt-templates"
  - "--no-context-files"
  - "--tools"
  - "system-prompt"
  - *sysprompt
  - "read, web_search" # TODO: add mcp tools here
subprocess_kwargs:
  # defaults, hardcoded in code:
  # TODO: is this correct? Should we communicate via the default pipe with the agent?
  # stdin: subprocess.PIPE
  # stdout: subprocess.PIPE
  # test: True
